name: 'build'

on: 
  workflow_dispatch:

jobs:
  build-qemu-windows:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}  # Using MSYS2 shell for commands

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          cache: true
          msystem: MINGW64  # Set MSYS2 system to MINGW64 for cross-compiling
          install: >-
            diffutils
            git
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-libgcrypt
            mingw-w64-x86_64-libiconv
            mingw-w64-x86_64-libslirp
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-gtk3
            mingw-w64-x86_64-pixman
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-python
            mingw-w64-x86_64-SDL2

      - name: Configure QEMU
        run: |
          # Modify meson build script to allow multiple definitions
          sed -z -i "s/qemu_ldflags = \[\]/qemu_ldflags = \['-liconv','-Wl,--allow-multiple-definition'\]/g" meson.build
          
          # Display configuration options
          echo "Configuration options:"
          ./configure --help
          
          # Run configure with the desired flags
          ./configure \
              --bindir=xtensa-softmmu \
              --datadir=share/qemu \
              --enable-gcrypt \
              --enable-iconv \
              --enable-gtk \
              --enable-pixman \
              --disable-sdl \
              --enable-strip \
              --enable-slirp \
              --enable-stack-protector \
              --extra-cflags="-static" \
              --extra-ldflags="-static" \
              --prefix=${PWD}/install/qemu \
              --target-list=xtensa-softmmu \
              --with-suffix="" \
              --without-default-features \
          || { cat meson-logs/meson-log.txt && false; }

      - name: Build
        run: |
          ninja -C build install
      - name: Package
        run: |
          find $PWD/install/qemu/share/qemu/ -maxdepth 1 -mindepth 1 -not -name 'esp32*.bin' -exec rm -rfv {} \;
          export DIST_DIR=${PWD}/dist
          mkdir -p ${DIST_DIR}
          cd $PWD/install
          mv qemu/share/qemu qemu/share/qemu-firmware
          ARCHIVE_NAME=QEMU_ESP32.tar.xz
          tar -cJvf ${DIST_DIR}/${ARCHIVE_NAME} qemu

      - name: Dist artifacts (${{ matrix.target }} @ ${{ matrix.platform }})
        uses: actions/upload-artifact@v4
        with:
          # TODO split artifacts for tests
          name: dist-qemu-${{ matrix.target }}-${{ matrix.platform }}
          path: |
            install/qemu


